
dialect "java"

import org.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;
import domain.Cell

global SimpleScoreHolder scoreHolder;

// Task 0
// rule "hello cell"
//     when
//        $cell_1 : Cell(row == 2)
//     then
//        System.out.println($cell_1);
//        scoreHolder.addConstraintMatch(kcontext, 0);
// end

// Task 1
// rule "all eights"
//    when
//        Cell(value != 8)
//    then
//        scoreHolder.addConstraintMatch(kcontext, -1);
// end

// Task 2
rule "unique values for each cell in a row"
     when
        $cell_1 : Cell()
        $cell_2 : Cell(row == $cell_1.row, column != $cell_1.column, value == $cell_1.value)
    then
        scoreHolder.addConstraintMatch((org.kie.api.runtime.rule.RuleContext) kcontext, -1);
end

rule "unique values for each cell in a column"
    when
        $cell_1 : Cell()
        $cell_2 : Cell(column == $cell_1.column, row != $cell_1.row, value == $cell_1.value)
    then
        scoreHolder.addConstraintMatch((org.kie.api.runtime.rule.RuleContext) kcontext, -1);
end

// Task 3

rule "unique values for each region"
    when
        // TODO implement
    then
        // TODO implement
end